name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use CMake ${{ matrix.node-version }}
      uses: actions/setup-cmake@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: sudo apt install cmake make
      
    - name: build 
      run: mkdir build && cd build && cmake -H../ -B. 
      
    - name: Make build 
      run: make 
    - name: Run app 
      run: ./MyExample 
    - name: Run tests
      run: make test
