name: CMake CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    - run: mkdir -p build
    - uses: actions/upload-artifact@v4
      with:
          name: my-artifact
          path: build
          
    - name: Install CMake
      run: sudo apt-get install -y cmake
    
    - name: Configure CMake
      run: cmake -S . -B build

  build:
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: build
      
      - name: Build
        run: cmake --build build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: ctest --test-dir build
