name: CMake CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cmake-configure:
    name: Cmake Configure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install CMake
      run: sudo apt-get install -y cmake
    
    - name: Configure CMake
      run : |
        mkdir -p build
        cmake -S . -B build

    - name: Save build artifacts
      uses: actions/upload-artifact@v2
      with:
          name: my-artifact
          path: build

  cmake-build:
    name: Cmake build
    runs-on: ubuntu-latest
    needs: cmake-configure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifacys
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: build
      
      - name: Cmake Build
        run: cmake --build build

  test:
    runs-on: ubuntu-latest
    needs: cmake-build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: ctest --test-dir build
